{ inputs, pkgs, ... }:
let
  system = pkgs.stdenv.hostPlatform.system;
  zedCompat = pkgs.runCommand "zed-compat" { } ''
    mkdir -p "$out/bin"
    ln -s "${pkgs.zed-editor}/bin/zeditor" "$out/bin/zed"
  '';
in
{
  environment.systemPackages = with pkgs; [
    pay-respects
    mosh
    doggo
    nixfmt
    nixfmt-tree
    fzf
    bat
    devenv
    carapace
    cmake
    cmatrix
    podman
    podman-compose
    eza
    fastfetch
    fd
    ffmpeg
    fish
    gcc
    gnupg
    kubernetes-helm
    helmfile
    kubectl
    lima
    minikube
    nasm
    neovim
    ninja
    nodejs
    openssh
    openssl
    qemu
    ripgrep
    rustup
    sqlite
    starship
    stow
    tmux
    typescript-go
    unzip
    wakeonlan
    python3
    wget
    xh
    xz
    yazi
    yt-dlp
    zoxide
    caddy
    nixd
    doppler
    tea
    jujutsu
    pass
    secretspec
    opencode
    go
    gopls
    delve
    air
    bun
    parallel
    trunk
    cargo-generate
    zed-editor
    zedCompat

    inputs.silicate.packages.${system}.default
    inputs.herdr.packages.${system}.default
    inputs.clonee.packages.${system}.default
    inputs.fast.packages.${system}.default
    inputs.helium.packages.${system}.default
  ];
}
